services:
  backend:
    build: backend/
    ports:
      - 3000:3000
    networks:
      - devchallenge

  frontend:
    build: frontend/
    ports:
      - 8080:8080
    networks:
      - devchallenge
      
networks:
  devchallenge: